version: 2
updates:
  - package-ecosystem: "cargo"
    # Look for `Cargo.toml` and `Cargo.lock` in the root directory
    directory: "/"
    # Check for updates every Monday
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
  - package-ecosystem: "github-actions"
    directory: "/"
    # Check for updates every Monday
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
